### ISSUE TITLE
Feature request: Possibility to update regex configuration from local python

### ISSUE THREAD

**Issue by ewandel** [cgrossde/rex#1]
Hi cgrossde,
this is a great chrome extension. I would love to have the feature that a local python process can send an update for the regular expressions which are highlighted. Could this be implemented? This is a related discussion which I found: https://stackoverflow.com/questions/61252039/message-passing-to-chrome-extension-from-local-python

Thanks for the great extension!

**Comment by cgrossde** [comment]
Feel free to open a PR 😉
